name: Docker Build ARM64 (On Demand)

on:
  workflow_dispatch:
    inputs:
      build_arm64:
        description: 'Build ARM64 images'
        required: true
        default: true
        type: boolean
  push:
    tags:
      - 'v*'
  schedule:
    # Build ARM64 once a week to keep cache warm
    - cron: '0 2 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/cert-agent

jobs:
  build-arm64:
    name: Build ARM64 Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=arm64,enable=true

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=arm64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/cert-agent:buildcache-arm64
          cache-to: |
            type=gha,mode=max,scope=arm64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/cert-agent:buildcache-arm64,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
